{% set name = "kalendar" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kalendar-{{ version }}.tar.gz
  sha256: ebd8908617c70acb3b383dd8f36521a2a8497fe9e6ee7a50236353ff7a285bd2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8

test:
  imports:
    - kalendar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OCHA-DAP/kalendar
  summary: Datetime extensions for dekadal data
  description: |
    In climatology, data is often reported in multi-day formats,
    such as dekads (a 10 day definition) or pentads (a 5 day definition).
    kalendar is a Python package with datetime.date extensions for
    dekadal and pentadal calendar definitions that make it easier to
    work with such climate data.
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://kalendar.readthedocs.io/
  dev_url: https://github.com/OCHA-DAP/kalendar

extra:
  recipe-maintainers:
    - caldwellst
